### ISSUE TITLE
IV network - No metadat available

### ISSUE THREAD

**Issue by aubercor** [EIDA/userfeedback#107] opened 2021-09-15 11:08 UTC
Hello,

It seems there is no metadata available for the IV network.

Here is my code and result:

```
from obspy.clients.fdsn import RoutingClient                                                                                                                                              

rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './EidaToken/eidatoken'})                                                          

inv = rsClient.get_stations(network="IV", sta="*", loc="*", channel="*",level="response")                                                                                                 

inv   

#### Result ######                                                                                                                                                                                    
Inventory created at 2021-09-15T09:28:05.033646Z
	Created by: ObsPy 1.2.2
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.2.2
	Contains:
		Networks (0):

		Stations (0):

		Channels (0):
```

Do you have any idea? 

Regards,
Coralie

**Comment by javiquinte** [comment] 2021-09-15 11:11
Thanks for letting us know, @aubercor 
We will come back to you as soon as we identify the problem.

**Comment by massimo1962** [comment] 2021-09-15 12:36
@aubercor at the moment we have this limit on our production service; the problem is related to the database limits - I think that if you want the whole network at response level you have to split the request.
In any case we are working on it and in a while we put a new version able to do this query.

**Comment by damb** [comment] 2021-09-15 14:51
@aubercor, use `eidaws-federator`, instead. The service implements the `fdsnws-station` API - therefore it should work with obspy, too. E.g.

```py
from obspy.clients.fdsn import Client

client = Client('http://eida-federator.ethz.ch')
inventory = client.get_stations(network="IV", level="response")
```

**Comment by aubercor** [comment] 2021-09-16 10:16
Hello damb and massimo,

Thanks for your reply.
I tried the lines sent by Damb but it does not work neither:

```
from obspy.clients.fdsn import Client
client = Client('http://eida-federator.ethz.ch')
inventory = client.get_stations(network="IV", level="response")

Unknown Error (timeout): timed out
```

Moreover, I would like to use specifically the RoutingClient from EIDA.

The splitting option mentioned by massimo is interesting but I noticed that when using the RoutingClient from EIDA, it is not possible to split the request (sta=* or sta=1 station). The return is the same with both options: it downloads the whole network response.

I did several tests.

For example:

```
inv = rsClient.get_stations(network="FR", sta="*", loc="*", channel="*",level="response")   
is the same as
inv = rsClient.get_stations(network="FR", sta="OGAG", loc="*", channel="*",level="response")
```
inv = the whole network at the response level in both examples for FR network.

For IV network:

```
inv = rsClient.get_stations(network="IV", sta="*", loc="*", channel="*",level="response")   
is the same as
inv = rsClient.get_stations(network="IV", sta="ORO", loc="*", channel="*",level="response")
```
Response is the same for both requests:

```
Inventory created at 2021-09-15T09:28:05.033646Z
	Created by: ObsPy 1.2.2
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.2.2
	Contains:
		Networks (0):

		Stations (0):

		Channels (0):
```

It might be a problem with the obspy rsClient.get_stations in addition to the limit on production service mentioned by massimo.

Do you have the same result as me?

Regards,
Coralie

**Comment by damb** [comment] 2021-09-16 11:40
(I exclusively refer to my proposal using `eidaws-federator`):

> Moreover, I would like to use specifically the RoutingClient from EIDA.

`eidaws-federator` uses EIDA routing internally. No need to use it specifically when requesting data from `eidaws-federator`.

Also, you received a timeout (client-side). So please, increase the [timeout](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.__init__.html#obspy.clients.fdsn.client.Client.__init__) when creating a `Client` instance.

Once `eidaws-federator` caches are hot you should receive a response within about a minute. However, in case of a lot of cache misses you most probably hit timeouts. Note also that we are working on improving the performance of `fdsnws-station` requests issued to `eidaws-federator`.

**Comment by damb** [comment] 2021-09-16 12:08
> The return is the same with both options: it downloads the whole network response.

When using the [get_stations](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.__init__.html#obspy.clients.fdsn.client.Client.__init__) method from obspy's `RoutingClient` you MUST make sure that you're invoking the method correctly. I.e. while `eidaws-routing` service API understands both `network|net`, `station|sta`, `location|loc`, `channel|cha`, `starttime|start`, `endtime|end` the `get_stations` method doesn't when it comes to actually routing the request:

> Only the network, station, location, channel, starttime, and endtime parameters are used for the actual routing. These and all other arguments are then just passed on to each single fdsnws station implementation.

**Comment by aubercor** [comment] 2021-09-17 07:18
Hello Damb,

I found why I got into trouble.

I was running 

`inv = rsClient.get_stations(network="FR", sta="OGAG", loc="*", channel="*",level="response")
`
With the parameter sta=OGAG, I was getting the metadata of the whole FR network.

But with the parameter station="OGAG":

`inv = rsClient.get_stations(network="FR", station="OGAG", location="*", channel="*",level="response")`

I only get the FR.OGAG metadata as requested.

Thanks,
Coralie

**Comment by petrrr** [comment] 2021-10-01 09:56
Just reviewing this issue and we might want to push an issue to ObsPy, so that request styles remain consistent and either support both *extended* and *abbreviated* parameters or only the extended but do not mix. Otherwise this kind of problems might bite other clients.

And should we close this for the time being?

**Comment by damb** [comment] 2021-10-01 10:35
@petrrr, I already opened an ObsPy issue: https://github.com/obspy/obspy/issues/2881

**Comment by jschaeff** [comment] 2021-10-01 11:18
I agree to close the issue for now. We can get back to it later.

**Closed by jschaeff** 2021-10-01 11:18 UTC
Labels: node-INGV, Metadata

**Comment by aubercor** [comment] 2021-12-13 14:59
Hello,

It seems the problem to retrieve the inventory of the IV network is still on.

Here is my code and result:

```
from obspy.clients.fdsn import RoutingClient                                                                                                                                              
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './EidaToken/eidatoken'})                                                          
inv = rsClient.get_stations(network="IV", sta="*", loc="*", channel="*",level="response")          
```                                                                                       


#### Result ######                                                                                                                                                                                    
```
Inventory created at 2021-09-15T09:28:05.033646Z
	Created by: ObsPy 1.2.2
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.2.2
	Contains:
		Networks (0):

		Stations (0):

		Channels (0):

```

When using the fdsn client, there is a time out exception.

Do you know if it is going to be solved soon?

Regards,
Coralie

**Comment by massimo1962** [comment] 2021-12-16 09:41
Dear Coralie,
unfortunately we don't have the new system on line yet.
We are finishing the test and soon publish it.
Sorry for the inconvenience.
Regards
Massimo
