### ISSUE TITLE
[Metadata] Z3.A003A missing metadata

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#4] opened 2019-04-25 14:08 UTC
`http://www.orfeus-eu.org/fdsnws/station/1/query?&net=Z3&station=*&format=text&level=station`

When I execute this, station A003A from the Z3 network is missing. I already reported this personally to Mathijs at ODC node a couple of weeks ago, and he said there was some issue with the metadata synchronization among the nodes. For some while it seemed fixed and Z3.A003A metadata was discoverable, but now the metadata is missing again.

Please investigate ;)

**Comment by javiquinte** [comment] 2019-04-25 22:59
Hi! I assigned this to @Jollyfant but it should have been assigned also to @sheimers
I'll send a personal message to him.

**Comment by javiquinte** [comment] 2019-04-25 23:25
Actually, the source of this could come from the Routing Service. This station is missing from the following query output.
[http://www.orfeus-eu.org/eidaws/routing/1/query?format=post&net=Z3&sta=A00*](http://www.orfeus-eu.org/eidaws/routing/1/query?format=post&net=Z3&sta=A00*)

> http://www.orfeus-eu.org/fdsnws/dataselect/1/query
Z3 A009A * * 2015-01-01T00:00:00 2019-04-26
Z3 A008A * * 2015-01-01T00:00:00 2019-04-26
Z3 A007A * * 2015-01-01T00:00:00 2019-04-26
Z3 A006A * * 2015-01-01T00:00:00 2019-04-26
Z3 A005B * * 2016-05-25T14:00:00 2019-04-26
Z3 A005A * * 2015-01-01T00:00:00 2016-05-25T00:00:00
Z3 A004A * * 2015-01-01T00:00:00 2019-04-26
Z3 A002A * * 2015-01-01T00:00:00 2019-04-26
Z3 A001A * * 2015-01-01T00:00:00 2019-04-26

However, it is present in the local configuration at ODC. @Jollyfant did you add it in the last day? Did you see some error when you run updateAll.py from the Routing Service?

[http://www.orfeus-eu.org/eidaws/routing/1/localconfig](http://www.orfeus-eu.org/eidaws/routing/1/localconfig)

> ...
<ns0:route networkCode="Z3" stationCode="A002A" locationCode="*" streamCode="*">
<ns0:station address="http://www.orfeus-eu.org/fdsnws/station/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
<ns0:dataselect address="http://www.orfeus-eu.org/fdsnws/dataselect/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
<ns0:wfcatalog address="http://www.orfeus-eu.org/eidaws/wfcatalog/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
</ns0:route>
<ns0:route networkCode="Z3" stationCode="A003A" locationCode="*" streamCode="*">
<ns0:station address="http://www.orfeus-eu.org/fdsnws/station/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
<ns0:dataselect address="http://www.orfeus-eu.org/fdsnws/dataselect/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
<ns0:wfcatalog address="http://www.orfeus-eu.org/eidaws/wfcatalog/1/query" priority="1" start="2015-01-01T00:00:00" end=""/>
</ns0:route>
...

**Comment by Jollyfant** [comment] 2019-04-26 08:08
Actually I have had problems with this station for a long time and can't get it to show up on `FDSNWS` despite all my efforts. It's missing from routing because:

    WARNING:root:No stations found for streams Stream(n='Z3', s='A003A', l='*', c='*') in http://www.orfeus-eu.org/fdsnws/station/1/query

It's available in the SeisComP3 database:

    MariaDB [p-seiscomp-odc]> select COUNT(*) from Station where code = 'A003A';
    +----------+
    | COUNT(*) |
    +----------+
    |        1 |
    +----------+

In the station filtering options it's there:

    [Include station Z3.A003A]
    code = Z3.A003A.*.*
    restricted = true

But FDSNWS refuses to serve it. I have absolutely no idea.

**Comment by sheimers** [comment] 2019-04-26 08:57
I'm sorry but I can't find the problem on our system. A003A is in the inventory, in a file we downloaded from ODC together with all other ODC stations. Also key/station_Z3_A003A points to the same profile as other ODC stations, eg. A002A.


sysop@eida:/usr/local/etc$ cat key/station_Z3_A003A 
# Binding references
arclink:eidaODC
arclink-access:aabackbone
sysop@eida:/usr/local/etc$ cat key/arclink/profile_eidaODC 
# List of routes.
routes = odc

# List of streams this route applies to (optional, wildcarded). When indicated
# the streamCode will be generated in the routing entries.
routes.odc.streams = HH*,HG*,EH*,LH*,SH*

# host:port of Arclink server (required to enable the binding block).
routes.odc.arclink.address = eida.orfeus-eu.org:18002

**Comment by sheimers** [comment] 2019-04-26 09:10
One difference between A003A and other similar station is that its streams have <restricted>false</restricted>, while the station itself and other streams of other stations have <restricted>true</restricted>.  It seems not related, but maybe it confuses the system. The file was last importet January 16 of this year.

```
sysop@eida:/usr/local/etc$ grep restricted  inventory/Z3.ODC.xml  | grep false | wc -l
12
sysop@eida:/usr/local/etc$ grep restricted  inventory/Z3.ODC.xml  | grep true | wc -l
458

```

**Comment by Jollyfant** [comment] 2019-04-26 09:20
Could be.. @sheimers I've added the `restrictedStatus` field to the individual channels. So on next sync you should have it too.

**Comment by javiquinte** [comment] 2019-04-26 09:30
Thanks to you both @Jollyfant and @sheimers !
I'm closing this now as it seems the proper solution. Please, @flofux reopen it in case you don't find the station tomorrow

**Comment by flofux** [comment] 2019-04-29 09:24
Station is still missing :-/

**Comment by javiquinte** [comment] 2019-04-29 10:03
@Jollyfant confirmed me that restarting the web service could take some days.

**Comment by flofux** [comment] 2019-04-29 10:04
> @Jollyfant confirmed me that restarting the web service could take some days.

Alright, I'll bet a bit more patient ;)

**Comment by sheimers** [comment] 2019-04-29 10:08
On our side the inventory has been updated with resticted=true for all stations:

```
sysop@eida:/usr/local/etc$ grep restricted  inventory/Z3.ODC.xml  | grep true | wc -l
470
sysop@eida:/usr/local/etc$ grep restricted  inventory/Z3.ODC.xml  | grep false | wc -l
0
```

**Comment by Jollyfant** [comment] 2019-04-29 11:59
@flofux @javiquinte maintenance and service restart is scheduled for coming Thursday.

**Comment by javiquinte** [comment] 2019-04-29 16:01
OK. Closing again until Friday... :roll_eyes:

**Closed by javiquinte** 2019-04-29 16:01 UTC
Labels: ODC, StationWS

**Comment by Jollyfant** [comment] 2019-05-03 07:34
Confirmed: http://www.orfeus-eu.org/fdsnws/station/1/query?station=A003A
