### ISSUE TITLE
[No Data] Trying to download FR and GR data using fdsnws2sds

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/userfeedback#103] opened 2021-06-25 07:26 UTC
**Issue created on user's behalf:**

Dear EIDA Team,

I am using the fdsnws2sds tool to request waveform data and store it locally on my machine in an SDS structure. I am requesting data from the virtual network "_ALPARRAY", which works fine, and from other permanent networks complementing the AlpArray e.g. the networks "FR" and "GR".
My code to request data from "FR" looks as follows:

```
#!/bin/bash
net="FR"
sta="AGO,AJAC,ARBF,ARTF,ASEAF,BANN,BLAF,BOUC,BSTF,CALF,CFF,CHMF,CIEL,CLAF,COLF,CORF,EILF,ENAUX,ESCA,FLAF,GRN,ILLF,ILLK,ISO,LBL,LEMB,MLYF,MOF,MON,MORSI,MVIF,OG02,OG35,OGAG,OGCB,OGDI,OGGM,OGMO,OGMY,OGRV,OGS1,OGS2,OGS3,OGSA,OGSI,OGSM,OGVG,PLDF,PLYF,PRIMA,RIVEL,RONF,RSL,RUSF,SAOF,SAUF,SJAF,SMPL,SPIF,STR,SURF,SZBH,TRBF,TRIGF,TURF,WALT,WLS"
loc="*"
cha="HH?"  
start="2018-01-01T00:00:00Z"
end="2018-01-02T00:00:00Z"
outdir=~/data_FR/

fdsnws2sds -N${net} -S${sta} -L${loc} -C${cha} -s${start} -e${end} -v -o ${outdir}
```

With this I receive data for part of the requested stations, while I get an error message that data was not received for others:

```
record 6: blockette 1000 not found, stop reading
did not receive data from FR.AGO.00.HHE, FR.AGO.00.HHN, FR.AGO.00.HHZ, FR.ARTF.00.HHE, FR.ARTF.00.HHZ, FR.ASEAF.00.HHE, FR.ASEAF.00.HHN, FR.ASEAF.00.HHZ, FR.BANN.00.HHE, FR.BANN.00.HHN, FR.BANN.00.HHZ, FR.BLAF.00.HHE, FR.BLAF.00.HHN, FR.BLAF.00.HHZ, FR.BOUC.00.HHE, FR.BOUC.00.HHN, FR.BOUC.00.HHZ, ...
```

Also this error is not exactly reproducible, so every time I run the code the stations for which I do not receive data are varying.
Has a similar issue come up before ?
For any help on this I would be grateful.

Kind regards,
BB

**Comment by jschaeff** [comment] 2021-06-25 12:22
@andres-h can you tell me how to check the presence of this blockette ?

**Comment by jschaeff** [comment] 2021-06-25 13:02
For all files reported in the scrip output, there is at least one 1000 bloquette. Here is the count of them:
```
FR.AGO.00.HHN
2291
FR.AGO.00.HHZ
2291
FR.ARTF.00.HHE
5010
FR.ARTF.00.HHZ
4655
FR.ASEAF.00.HHE
3430
FR.ASEAF.00.HHN
2291
FR.ASEAF.00.HHZ
2597
FR.BANN.00.HHE
1
FR.BANN.00.HHN
1
FR.BANN.00.HHZ
2
FR.BLAF.00.HHE
5429
FR.BLAF.00.HHN
5449
FR.BLAF.00.HHZ
4846
FR.BOUC.00.HHE
2294
FR.BOUC.00.HHN
2302
FR.BOUC.00.HHZ
2292
```

As the error is not 100% reproducible, we should check that the dataselect service did transmit correctly the data ...

**Comment by andres-h** [comment] 2021-06-25 15:15
One 1000 blockette 1000 is not enough. There must be blockette 1000 in every record -- a record without blockette 1000 is not valid miniseed.

The blockette 1000 contains record length, so it is not possible to read the data without blockette 1000 (unless making assumptions). In case of full SEED, record length is indicated in full SEED headers, so blockette 1000 is not mandatory in full SEED.

Regarding reproducibility, fdsnws2sds downloads the data in random order, so each time it stumbles on this record at a different time.

msi is most convenient for checking the data, eg.:

<pre>
$ msi -ppp archive/2021/GE/WLF/BHZ.D/GE.WLF..BHZ.D.2021.176
GE_WLF__BHZ, 049862, D
             start time: 2021,176,00:00:11.149996
      number of samples: 417
     sample rate factor: 20  (20 samples per second)
 sample rate multiplier: 1
         activity flags: [00000000] 8 bits
    I/O and clock flags: [00000100] 8 bits
                         [Bit 5] Clock locked
     data quality flags: [00000000] 8 bits
   number of blockettes: 2
        time correction: 0
            data offset: 64
 first blockette offset: 48
         BLOCKETTE 1000: (Data Only SEED)
              next blockette: 56
                    encoding: STEIM 2 Compression (val:11)
                  byte order: Big endian (val:1)
               record length: 512 (val:9)
               reserved byte: 0
         BLOCKETTE 1001: (Data Extension)
              next blockette: 0
              timing quality: 100%
                micro second: 96
               reserved byte: 70
                 frame count: 7
...
</pre>

**Comment by BeneBraszus** [comment] 2021-08-30 13:49
Dear all,

have there been any updates regarding this issue ? 
similarly to @jbienkowski  I am requesting data from the virtual "_ALPARRAY" network as well as from "FR", "GR" and some other permanent networks. 
I am using a very similar code 

`fdsnws2sds -NGR -SWET -L* -CHHE -s2019-01-07T00:00:00.000000Z -e2019-01-08T00:00:00.000000Z -v -o ~/data_BGR/007_007_2019 `

and am getting the same error as reported above: 
`record 1: blockette 1000 not found, stop reading`
`did not receive data from GR.WET..HHE`

So far I only observed the issue for data from the "GR" network.

When requesting the data e.g. with the Obspy FDSN Client, there does not seem to be an issue:

```
from obspy.clients.fdsn import Client
from obspy.core import read, UTCDateTime

cl  = Client("BGR")
st  = cl.get_waveforms(network = "GR", station = "WET", location = "*", channel = "HH*",\
                              starttime = UTCDateTime(2019,1,7,0,0,0), endtime = UTCDateTime(2019,1,8,0,0,0)) 
print(st)
```
```
7 Trace(s) in Stream:
GR.WET..HHE | 2019-01-07T00:00:00.000000Z - 2019-01-07T11:49:40.910000Z | 100.0 Hz, 4258092 samples
GR.WET..HHE | 2019-01-07T11:49:49.559999Z - 2019-01-07T23:59:59.999999Z | 100.0 Hz, 4381045 samples
GR.WET..HHN | 2019-01-07T00:00:00.000000Z - 2019-01-07T11:49:34.890000Z | 100.0 Hz, 4257490 samples
GR.WET..HHN | 2019-01-07T11:49:43.819999Z - 2019-01-07T23:59:59.999999Z | 100.0 Hz, 4381619 samples
GR.WET..HHZ | 2019-01-07T00:00:00.000000Z - 2019-01-07T11:49:34.790000Z | 100.0 Hz, 4257480 samples
GR.WET..HHZ | 2019-01-07T11:49:43.720000Z - 2019-01-08T00:00:00.000000Z | 100.0 Hz, 4381629 samples
GR.WET..HHZ | 2019-01-08T00:00:00.000000Z - 2019-01-08T00:00:00.000000Z | 100.0 Hz, 1 samples
```

Kind regards,
Benedikt Braszus

**Comment by jschaeff** [comment] 2021-08-30 14:36
On my part, I scanned all the FR archive of 2018-01-01 (from the list initial list of streams) and I can confirm that all file has at least one bloquette 1000.

```sh
for station in AGO AJAC ARBF ARTF ASEAF BANN BLAF BOUC BSTF CALF CFF CHMF CIEL CLAF COLF CORF EILF ENAUX ESCA FLAF GRN ILLF ILLK ISO LBL LEMB MLYF MOF MON MORSI MVIF OG02 OG35 OGAG OGCB OGDI OGGM OGMO OGMY OGRV OGS1 OGS2 OGS3 OGSA OGSI OGSM OGVG PLDF PLYF PRIMA RIVEL RONF RSL RUSF SAOF SAUF SJAF SMPL SPIF STR SURF SZBH TRBF TRIGF TURF WALT WLS; do
       for f in $(find /mnt/nfs/summer/validated_seismic_data/FR/2018/$station/HH*.D/*.001); do
           msi -ppp $f | grep -e "^0$"  && echo "no bloquette 1000 for file $f"
       done
done
```

This code snippet did not return any result.

**Comment by andres-h** [comment] 2021-09-14 12:46
Strictly speaking, data without blockette 1000 is not valid MiniSEED, because that blockette contains the record length, encoding, etc. If the blockette 1000 is missing, full SEED headers must be used.

fdsnws_fetch quits as soon as a record without blockette 1000 is found, because without knowing the record length it cannot read the data.

It would be possible to determine the record length without blockette 1000 by searching for the beginning of the next record. This is what Obspy probably does. We will try to improve fdsnws_fetch in this regard.

**Comment by andres-h** [comment] 2022-02-11 14:48
I found a bug in fdsnws_fetch, namely it looked at the first blockette only. While b1000 is almost always the first blockette in MiniSEED, it turned out to be not always the case. The script in OP works now, so I'm closing this issue. The latest version of fdsnwsscripts can be obtained from [github](https://github.com/GEOFON/fdsnws_scripts) or [pypi](https://pypi.org/project/fdsnwsscripts/).

**Closed by andres-h** 2022-02-11 14:48 UTC
Labels: node-RESIF

**Comment by jschaeff** [comment] 2022-02-11 16:15
That's great news !  Thanks @andres-h  for spotting the bug and solving the issue ! :+1:
