### ISSUE TITLE
[Service] Swarm software does not connect to eida.rm.ingv.it any more

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/userfeedback#37] opened 2019-11-18 08:42 UTC
Dear team,

This issue has been created on behalf of one of our users:

> I have a problem that I hope to solve, before connecting Network-IV with the MiniSeed-"Swarm Software" to Host `eida.rm.ingv.it`, but it no longer connects. Please if they have changed give me the new Host server.

**Comment by javiquinte** [comment] 2019-11-18 10:03
I thought that the cause was that `eida.rm.ingv.it` was a deprecated domain name, and that `eida.ingv.it` has to be used. Despite this could actually be true (could you @massimo1962 confirm this?), this seems not to be the cause as both names resolve to the same IP.

> sec24-dynip-181:~ javier$ ping eida.rm.ingv.it
PING eida.ms.ingv.it (93.63.207.205): 56 data bytes
64 bytes from 93.63.207.205: icmp_seq=0 ttl=52 time=33.968 ms
64 bytes from 93.63.207.205: icmp_seq=1 ttl=52 time=36.741 ms
64 bytes from 93.63.207.205: icmp_seq=2 ttl=52 time=35.702 ms
^C
--- eida.ms.ingv.it ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 33.968/35.470/36.741/1.144 ms
sec24-dynip-181:~ javier$ ping eida.ingv.it
PING eida.ms.ingv.it (93.63.207.205): 56 data bytes
64 bytes from 93.63.207.205: icmp_seq=0 ttl=52 time=34.140 ms
64 bytes from 93.63.207.205: icmp_seq=1 ttl=52 time=34.609 ms
^C

Let's wait for @massimo1962 's answer...

**Comment by petrrr** [comment] 2019-11-18 19:29
@javiquinte: 
I'd like to reply on behalf of @massimo1962, because I already had this notification by other channels.

I guess there are some independent issues to clarify here:

* The host `eida` **by design** only would provide EIDA/Arclink service only, so it probably should never have worked with Swarm (unclear what the user refers to ???).
* The host `eida` (`eida.ingv.it` prefered, `eida.ms.ingv.it` reverse lookup, `eida.rm.ingv.it` legacy) has been obsoleted for EIDA services already quite some time back.
* EIDA/Arclink has been moved to host `eidaws` (`eidaws.ingv.it`, prefered). This change has declared through master table and announces as good as possible (we lack some more reliable channel here!).  
* As you noted the host is still active for internal reasons, but would currently not provide any official EIDA services;

FDSN and EIDA webservices are supported only through their canonical end points as specified on

* http://www.orfeus-eu.org/data/eida/nodes/INGV/

I therefore would suggest to close this issue as `invalid` or similar.

**Closed** 2019-11-20 11:13 UTC
Labels: INGV, invalid

**Comment by Thor0001** [comment] 2019-11-20 13:14
Good Day, until about 02 Weeks SWARM linked and displayed data through Host 'eida.rm.ingv.it' and also with FDSN ['http://eida.rm.ingv.it/fdsnws/dataselect/1/query' ] however it is no longer linked & obviously no show data. Simultaneously Host 'webservices.rm.ingv.it' only links to FDSN [http://webservices.rm.ingv.it/fdsnws/dataselect/1/query] but *no display data. The first part is a complicated issue to solve; then, can I ask any solution to receiving FDSN data with Swarm?. Thanks !.

**Comment by Thor0001** [comment] 2019-11-20 13:15
> @javiquinte:
> I'd like to reply on behalf of @massimo1962, because I already had this notification by other channels and replied to the user directly.
> 
> I guess there are some independent issues to clarify here:
> 
> * The host `eida` **by design** only would provide EIDA/Arclink service only, so it probably should never have worked with Swarm (unclear what the user refers to ???).
> * The host `eida` (`eida.ingv.it` prefered, `eida.ms.ingv.it` reverse lookup, `eida.rm.ingv.it` legacy) has been obsoleted for EIDA services already quite some time back.
> * EIDA/Arclink service has moved to host `eidaws` (`eidaws.ingv.it`, prefered). This change has been declared through master table and announces as good as possible (we lack some more reliable channel here!).
> * As you noted the host is still active for internal reasons, but would currently -- despite its name -- not provide any official EIDA services;
> 
> FDSN and EIDA webservices are supported only through their canonical end points as specified on
> 
> * http://www.orfeus-eu.org/data/eida/nodes/INGV/
> 
> I therefore would suggest to close this issue as `invalid` or similar.

Good Day, until about 02 Weeks SWARM linked and displayed data through Host 'eida.rm.ingv.it' and also with FDSN ['http://eida.rm.ingv.it/fdsnws/dataselect/1/query' ] however it is no longer linked & obviously no show data. Simultaneously Host 'webservices.rm.ingv.it' only links to FDSN [http://webservices.rm.ingv.it/fdsnws/dataselect/1/query] but *no display data. The first part is a complicated issue to solve; then, can I ask any solution to receiving FDSN data with Swarm?. Thanks !.

**Comment by javiquinte** [comment] 2019-11-21 12:15
I'm copy-pasting on behalf of @petrrr a detailed explanation regarding the usage of Swarm software. This explains clearly why this issue has been closed.

> "Unfortunately we currently cannot offer realtime data exchange to the general public or individual researchers due to resource limitations. 
> We offer such services only to collaborating institutional users on the base of bilateral agreements.
> This is necessary to ensure and protect the functionality of the officially supported services to institutional and scientific users.
> In the past we have seen abuse of our FDSNWS dataselect service by the Swarm client for continues 'pseudo realtime' data streaming. 
> The dataselect service and protocol were not designed for such a usage pattern which is extremely resource consuming on our systems and 
> the network infrastructure. We therefore now blocking requests from Swarm clients or similar usage patterns."
