### ISSUE TITLE
RESIF issues with EIDA token

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#38] opened 2019-12-02 09:48 UTC
Hi everyone,
it seems there are currently issues with accessing RESIF data using a token (even for data that doesn't require one). Whenever specifying a EIDA token during the request I run into an error. If I don't provide a token, everything seems fine. The station BOUC is just a random example, it seems to hold for any RESIF hosted station.

Note that currently there are also no French stations visible in e.g. the Stationbook: http://orfeus-eu.org/stationbook/

Here's a code sample:

```
from obspy import UTCDateTime
from obspy.clients.fdsn import RoutingClient
from obspy.clients.fdsn import Client

t1 = UTCDateTime('2018-03-21')
t2 = UTCDateTime('2018-03-22')

routed = RoutingClient('eida-routing', debug=True)
direct = Client('RESIF', debug=True)

direct.get_waveforms(network='FR', station='BOUC', location='*', channel='HH*', starttime=t1, endtime=t2)
```
3 Trace(s) in Stream:
FR.BOUC.00.HHE | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples
FR.BOUC.00.HHN | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples
FR.BOUC.00.HHZ | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples

```
routed.get_waveforms(network='FR', station='BOUC', location='*', channel='HH*', starttime=t1, endtime=t2)
```
3 Trace(s) in Stream:
FR.BOUC.00.HHE | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples
FR.BOUC.00.HHN | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples
FR.BOUC.00.HHZ | 2018-03-21T00:00:00.000000Z - 2018-03-22T00:00:37.710000Z | 100.0 Hz, 8643772 samples

```
routed_token = RoutingClient('eida-routing', debug=True, credentials={'EIDA_TOKEN': '/token/here'})
direct_token = Client('RESIF', debug=True, eida_token='/token/here')
```

```
direct_token.get_waveforms(network='FR', station='BOUC', location='*', channel='HH*', starttime=t1, endtime=t2)
```

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7fee0f42c358>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://ws.resif.fr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:

BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-12-22T10:55:44.932579Z", "cn": "Florian Fuchs", "memberof": "/epos/alparray;/epos;/", "sn": "Fuchs", "issued": "2019-11-22T10:55:44.932585Z", "mail": "florian.fuchs@univie.ac.at", "givenName": "Florian", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJd176wAAoJEEFpzp0AlwdX8t0H/0MpW6x9hiE1JLzly2qqeXe7
C2oTugdrgZAoBWqH3yBEiaeciRrIiDDtYV58OwokRADOuIHBLVxYvcEzqF3bG0wa
zm2mJ3r0XTQLe+GuLVHQm00d2mARYkx5202Adg1VenWOQZXPmO2sTMZNZ9dpoEhK
gn0Cn2U9x1kPRMEZJE2iN1AJmz4pnmHZBFppi7W2VW0cK20IcWyMrT22kjo6epk2
XOEyixwjDeSUUlGbGrBf/U3S3psk8UXOTqqAN/UrLXc+YgXPmqKbkQce+wsjRrrG
8e0jeTD0Xe/30Yy8HzPLEUFjaowC333URKQ8eBp97rXTgqdL6899L7UdPqDJuNM=
=bi4M
-----END PGP SIGNATURE-----

HTTP error 500, reason INTERNAL SERVER ERROR, while downloading 'https://ws.resif.fr/fdsnws/dataselect/1/auth': 500 Internal Server Error Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

FDSNException                         

FDSNException: Service responds: Internal server error
Detailed response of server:

```
routed_token.get_waveforms(network='FR', station='BOUC', location='*', channel='HH*', starttime=t1, endtime=t2)
```

Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:

service=station
format=post
alternative=false
FR BOUC * HH* 2018-03-21T00:00:00.000000 2018-03-22T00:00:00.000000

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7fee0f80b470>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://ws.resif.fr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:

BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-12-22T10:55:44.932579Z", "cn": "Florian Fuchs", "memberof": "/epos/alparray;/epos;/", "sn": "Fuchs", "issued": "2019-11-22T10:55:44.932585Z", "mail": "florian.fuchs@univie.ac.at", "givenName": "Florian", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJd176wAAoJEEFpzp0AlwdX8t0H/0MpW6x9hiE1JLzly2qqeXe7
C2oTugdrgZAoBWqH3yBEiaeciRrIiDDtYV58OwokRADOuIHBLVxYvcEzqF3bG0wa
zm2mJ3r0XTQLe+GuLVHQm00d2mARYkx5202Adg1VenWOQZXPmO2sTMZNZ9dpoEhK
gn0Cn2U9x1kPRMEZJE2iN1AJmz4pnmHZBFppi7W2VW0cK20IcWyMrT22kjo6epk2
XOEyixwjDeSUUlGbGrBf/U3S3psk8UXOTqqAN/UrLXc+YgXPmqKbkQce+wsjRrrG
8e0jeTD0Xe/30Yy8HzPLEUFjaowC333URKQ8eBp97rXTgqdL6899L7UdPqDJuNM=
=bi4M
-----END PGP SIGNATURE-----

HTTP error 500, reason INTERNAL SERVER ERROR, while downloading 'https://ws.resif.fr/fdsnws/dataselect/1/auth': 500 Internal Server Error Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

obspy.clients.fdsn.header.FDSNException: Service responds: Internal server error
Detailed response of server:

  r["data_type"], r["endpoint"], reason))
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:

service=dataselect
format=post

FDSNNoDataException                      
 
FDSNNoDataException: No data available for request.
Detailed response of server:

No Content --

**Comment by jschaeff** [comment] 2019-12-03 08:45
OK, I'm looking into this.

**Comment by jschaeff** [comment] 2019-12-03 13:51
I think I fixed the problem. Could you let me know ?

**Comment by flofux** [comment] 2019-12-03 13:57
Seems to be working now. Thank you very much! :)

**Comment by okling** [comment] 2019-12-11 10:47
Hi all, I'm having the same issue. I'm using Python v3.7.3 and Obspy v1.1.1.

This is the example python code I have:

```
from obspy import UTCDateTime
from obspy.clients.fdsn import RoutingClient
from obspy.clients.fdsn import Client
starttime = UTCDateTime("2019-11-20 04:27:00")
endtime = starttime + 3600

direct = Client('RESIF', debug=True)
```
I immediately received the error message
```
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f335d3ad278>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid, Python 3.7.3)'}
Downloading http://ws.resif.fr/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/contributors with requesting gzip compression
HTTP error 404, reason Not Found, while downloading 'http://ws.resif.fr/fdsnws/event/1/application.wadl': b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /fdsnws/event/1/application.wadl was not found on this server.</p>\n</body></html>\n'
Downloaded http://ws.resif.fr/fdsnws/dataselect/1/application.wadl with HTTP code: 200
Downloaded http://ws.resif.fr/fdsnws/station/1/application.wadl with HTTP code: 200
HTTP error 404, reason Not Found, while downloading 'http://ws.resif.fr/fdsnws/event/1/catalogs': b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /fdsnws/event/1/catalogs was not found on this server.</p>\n</body></html>\n'
HTTP error 404, reason Not Found, while downloading 'http://ws.resif.fr/fdsnws/event/1/contributors': b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /fdsnws/event/1/contributors was not found on this server.</p>\n</body></html>\n'
Discovered dataselect service
Discovered station service
Storing discovered services in cache.
```
I tried it anyway with this line:
```
st = direct.get_waveforms(network='FR', station='*', location='*', channel='HHZ', starttime=starttime, endtime=endtime)
```
And it returned this error message:
```
Downloading http://ws.resif.fr/fdsnws/dataselect/1/query?starttime=2019-11-20T04%3A27%3A00.000000&endtime=2019-11-20T05%3A27%3A00.000000&network=FR&station=%2A&location=%2A&channel=HHZ without requesting gzip compression
Downloaded http://ws.resif.fr/fdsnws/dataselect/1/query?starttime=2019-11-20T04%3A27%3A00.000000&endtime=2019-11-20T05%3A27%3A00.000000&network=FR&station=%2A&location=%2A&channel=HHZ with HTTP code: 204
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 831, in get_waveforms
    data_stream = self._download(url, use_gzip=False)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1383, in _download
    raise_on_error(code, data)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1707, in raise_on_error
    server_info)
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
Detailed response of server:
```

Next, I tried to download the data with EIDA token:
```
direct_token = Client('RESIF', debug=True, eida_token='/home/aling/eidatoken')
```
Received error message again:
```
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f335d3d56a0>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://ws.resif.fr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-12-27T21:37:35.338200Z", "cn": "Angel Ling", "memberof": "/epos/alparray;/epos;/", "sn": "Ling", "issued": "2019-11-27T21:37:35.338207Z", "mail": "angel.ling@erdw.ethz.ch", "givenName": "Angel", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJd3uyfAAoJEEFpzp0AlwdXxtIIAIJTnhljK6IpFeYj9hO+w1NW
pBob3OZprcfFDBYypS3rrSo7VmqhaQDYgkEy8xjJPVhRo+HHIIs/6zgY5UXlb94d
CbbH3DSrD0iZXl+kolte1ZRwv9e5Gp398YdQFvuX34v86kxJIeD7P+XLQp07jhEJ
NZJisf1CyjlWMwdRnmdlQgRwI5mD854qJjVajJi6cpqvGCGdjASuaQWsx0w9vp3m
jGvK0y8mDuPmVZPSHUoQpo7Q4hnPfSZ8e0pAAHBFpvv5rdIywAa5aKL6X/sKr2y2
TIdp3OGghj2GlwbDpfFr/CWBVUfiF1BfQQ587Xf82PO3kmyrQ8pwmufuIEZRfKw=
=F+eB
-----END PGP SIGNATURE-----

----------------------------------------------------------------------
Downloaded https://ws.resif.fr/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: YBRMOGCX92ARKO/DUWT9WJE2EU4KF
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x7f335c3087b8>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x7f335c308ac8>]
>>> routed_token = RoutingClient('eida-routing', debug=True, credentials={'EIDA_TOKEN': '/home/aling/eidatoke/'})
>>> st = direct_token.get_waveforms(network='FR', station='*', location='*', channel='HHZ', starttime=starttime, endtime=endtime)
Downloading http://ws.resif.fr/fdsnws/dataselect/1/queryauth?starttime=2019-11-20T04%3A27%3A00.000000&endtime=2019-11-20T05%3A27%3A00.000000&network=FR&station=%2A&location=%2A&channel=HHZ without requesting gzip compression
Downloaded http://ws.resif.fr/fdsnws/dataselect/1/queryauth?starttime=2019-11-20T04%3A27%3A00.000000&endtime=2019-11-20T05%3A27%3A00.000000&network=FR&station=%2A&location=%2A&channel=HHZ with HTTP code: 204
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 831, in get_waveforms
    data_stream = self._download(url, use_gzip=False)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1383, in _download
    raise_on_error(code, data)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1707, in raise_on_error
    server_info)
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
Detailed response of server:
```
Again with routed token:
```
routed_token.get_waveforms(network='FR', station='*', location='*', channel='HHZ', starttime=starttime, endtime=endtime)
```
```
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=station
format=post
alternative=false
FR * * HHZ 2019-11-20T04:27:00.000000 2019-11-20T05:27:00.000000
----------------------------------------------------------------------
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f33698e1668>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid, Python 3.7.3)'}
Loading discovered services from cache.
/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py:99: UserWarning: Failed to download data of type 'station' from 'http://ws.resif.fr' due to: 
Traceback (most recent call last):
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 94, in _try_download_bulk
    return _download_bulk(r)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 122, in _download_bulk
    c.set_eida_token(r["credentials"]["EIDA_TOKEN"])
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 312, in set_eida_token
    user, password = self._resolve_eida_token(token)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 362, in _resolve_eida_token
    raise ValueError(msg)
ValueError: EIDA token does not seem to be a valid PGP message. If you passed a filename, make sure the file actually exists.

  r["data_type"], r["endpoint"], reason))
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=dataselect
format=post
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/decorator.py:decorator-gen-57>", line 2, in get_waveforms
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 82, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "</home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/decorator.py:decorator-gen-56>", line 2, in get_waveforms
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 89, in _assert_attach_response_not_in_kwargs
    return f(*args, **kwargs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 334, in get_waveforms
    return self.get_waveforms_bulk([bulk], **kwargs)
  File "</home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/decorator.py:decorator-gen-60>", line 2, in get_waveforms_bulk
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 82, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "</home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/decorator.py:decorator-gen-59>", line 2, in get_waveforms_bulk
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 89, in _assert_attach_response_not_in_kwargs
    return f(*args, **kwargs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/eidaws_routing_client.py", line 117, in get_waveforms_bulk
    r = self._download(self._url + "/query", data=bulk_str)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/base.py", line 245, in _download
    self._handle_requests_http_error(r)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 303, in _handle_requests_http_error
    raise_on_error(r.status_code, buf)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1707, in raise_on_error
    server_info)
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
Detailed response of server:

No Content -- 
```

**Comment by jschaeff** [comment] 2019-12-11 14:42
Hi,
about 
```
HTTP error 404, reason Not Found, while downloading 'http://ws.resif.fr/fdsnws/event/1/application.wadl': b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /fdsnws/event/1/application.wadl was not found on this server.</p>\n</body></html>\n'
```
It's normal as RESIF does not provide any event webservice.
From our availability webservice, I can see that you should get some data.
From your log I can see that you got a temporary user/password for queryauth.

The problem is that you get a 204 return code instead of getting data. I'm checking on it.

**Comment by jschaeff** [comment] 2019-12-12 19:48
We had some internal problems in our database. This is fixed now. Thank you for reporting it and sorry about the inconveniences.

http://ws.resif.fr/fdsnws/dataselect/1/query?starttime=2019-11-20&endtime=2019-11-21&network=FR&channel=HHZ

**Closed** 2019-12-12 21:04 UTC
Labels: Authentication/Authorization, RESIF

**Comment by okling** [comment] 2019-12-13 10:53
Yes, it works now. Thanks for your help!
