### ISSUE TITLE
[No Data] Missing AlpArray data

### ISSUE THREAD

**Issue by okling** [EIDA/userfeedback#77] opened 2020-10-21 10:01 UTC
Client: ObsPy 1.2.2, EIDA Routing Client, Python 3.7.3
Network: Z3
Date: Oct 20, 2020

When I was downloading some more AlpArray station waveforms, I found that some stations are missing, which were present when I was downloading a while back. 

This is the setup I have:
```
>>>from obspy.clients.fdsn import RoutingClient 
>>>from obspy import UTCDateTime
>>>rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': '/eidatoken'})
>>>starttime = UTCDateTime(2018,8,15,21,56,0)
>>>endtime   = UTCDateTime(2018,8,15,21,59,0)
```

This is the example how I was trying to download the waveform data (A217A):
```
>>>st = rsClient.get_waveforms(starttime=starttime, endtime=endtime, station="A217A", network="Z3", loc="*", channel="HHZ")
>>> print(st)
0 Trace(s) in Stream:
```

No error was shown. So I tried it again in debug mode:
```
>>> rsClient = RoutingClient("eida-routing", debug=True, credentials={'EIDA_TOKEN': '/eidatoken'})
>>> st = rsClient.get_waveforms(starttime=starttime, endtime=endtime, station="A217A", network="Z3", loc="*", channel="HHZ")
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=station
format=post
alternative=false
Z3 A217A * HHZ 2018-08-15T21:56:00.000000 2018-08-15T21:59:00.000000
----------------------------------------------------------------------
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f69c2306fd0>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.2.2 (Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid, Python 3.7.3)'}
Downloading http://ws.resif.fr/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://ws.resif.fr/fdsnws/event/1/contributors with requesting gzip compression
Downloaded http://ws.resif.fr/fdsnws/dataselect/1/application.wadl with HTTP code: 200
Downloaded http://ws.resif.fr/fdsnws/station/1/application.wadl with HTTP code: 200
Downloaded http://ws.resif.fr/fdsnws/event/1/contributors with HTTP code: 200
Downloaded http://ws.resif.fr/fdsnws/event/1/application.wadl with HTTP code: 200
Downloaded http://ws.resif.fr/fdsnws/event/1/catalogs with HTTP code: 200
Discovered dataselect service
Discovered station service
Discovered event service
Storing discovered services in cache.
Downloading https://ws.resif.fr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2020-10-30T15:15:29.945436Z", "cn": "Angel Ling", "memberof": "/epos/alparray;/epos;/", "sn": "Ling", "issued": "2020-09-30T15:15:29.945443Z", "mail": "angel.ling@erdw.ethz.ch", "givenName": "Angel", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
-----END PGP SIGNATURE-----

----------------------------------------------------------------------
Downloaded https://ws.resif.fr/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: JH3BQHGMPL9HFY/TK7QEROSCRC9EM
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x7f69c2318780>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x7f69c2318828>]
Downloading http://ws.resif.fr/fdsnws/station/1/query with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
format=text
level=channel
Z3 A217A * HHZ 2018-08-15T21:56:00 2018-08-15T21:59:00
----------------------------------------------------------------------
Downloaded http://ws.resif.fr/fdsnws/station/1/query with HTTP code: 200
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=dataselect
format=post
Z3 A217A 00 HHZ 2018-08-15T21:56:00.000000 2018-08-15T21:59:00.000000
----------------------------------------------------------------------
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f69c13cf1d0>]
Base URL: http://ws.resif.fr
Request Headers: {'User-Agent': 'ObsPy/1.2.2 (Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://ws.resif.fr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2020-10-30T15:15:29.945436Z", "cn": "Angel Ling", "memberof": "/epos/alparray;/epos;/", "sn": "Ling", "issued": "2020-09-30T15:15:29.945443Z", "mail": "angel.ling@erdw.ethz.ch", "givenName": "Angel", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
-----END PGP SIGNATURE-----

----------------------------------------------------------------------
Downloaded https://ws.resif.fr/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: JH3BQHGMPL9HFY/TK7QEROSCRC9EM
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x7f69c137c2b0>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x7f69c137c8d0>]
Downloading http://ws.resif.fr/fdsnws/dataselect/1/queryauth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
Z3 A217A 00 HHZ 2018-08-15T21:56:00 2018-08-15T21:59:00
----------------------------------------------------------------------
/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py:99: UserWarning: Failed to download data of type 'waveform' from 'http://ws.resif.fr' due to: 
Traceback (most recent call last):
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1791, in download_url
    url_obj = opener.open(request, timeout=timeout, data=data)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1088, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1102, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1207, in http_error_401
    host, req, headers)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/urllib/request.py", line 1082, in http_error_auth_reqed
    headers, None)
urllib.error.HTTPError: HTTP Error 401: digest auth failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 94, in _try_download_bulk
    return _download_bulk(r)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 137, in _download_bulk
    return fct(bulk_str + r["bulk_str"])
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1024, in get_waveforms_bulk
    data=bulk)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1396, in _download
    timeout=self.timeout, use_gzip=use_gzip)
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/clients/fdsn/client.py", line 1796, in download_url
    (e.code, str(e.reason), url, e.read())
  File "/home/aling/anaconda3/envs/obspy/lib/python3.7/tempfile.py", line 475, in __getattr__
    file = self.__dict__['file']
KeyError: 'file'

  r["data_type"], r["endpoint"], reason))
```

I did some further investigations and found a bunch of other stations:

- Z3.A151A, Z3.A152A, Z3.A153A, Z3.A154A, Z3.A155A, Z3.A156A, Z3.A157B, Z3.A158A, Z3.A159A
- Z3.A160A, Z3.A161A, Z3.A162A, Z3.A163A, Z3.A164A, Z3.A165A, Z3.A166B, Z3.A167A, Z3.A168A, Z3.A169A
- Z3.A170A, Z3.A171A, Z3.A172A, Z3.A173A, Z3.A174A, Z3.A175A, Z3.A176A, Z3.A177A, Z3.A179A
- Z3.A180A, Z3.A181A, Z3.A182A, Z3.A183A, Z3.A184A, Z3.A187A, Z3.A188A
- Z3.A190A, Z3.A191A, Z3.A192B, Z3.A193A, Z3.A194A, Z3.A195A, Z3.A196A, Z3.A199A
- Z3.A200A, Z3.A201A, Z3.A202A, Z3.A204A, Z3.A205A, Z3.A206A, Z3.A208A, Z3.A209B
- Z3.A212A, Z3.A213A, Z3.A215A, Z3.A217A

It happens from time to time. Any ideas on this? Thanks for your help!

**Comment by javiquinte** [comment] 2020-10-21 10:10
Hi @okling .
Thanks for the feedback! We are checking it and will come back to you ASAP.

**Comment by jschaeff** [comment] 2020-10-26 09:26
Hi, I'm investigating today.

**Comment by jschaeff** [comment] 2020-10-26 14:26
I am able to reproduce the problem with an EIDA token or with a classical login.
I can see a lot of requests failing the same way but not all of them and I try to understand what's wrong.
Thank you for your patience, I'm still on it.

**Comment by okling** [comment] 2020-10-26 14:28
@jschaeff Thanks for the update!

**Comment by jschaeff** [comment] 2020-10-26 15:22
@okling can you give another try now ?
Can you tell me when the data was not accessible ? And when it was ?

**Comment by okling** [comment] 2020-10-26 15:37
@jschaeff It works now! Thanks!

I don't continuously download data, so I can't really tell when exactly the data wasn't accessible. I remember I had the same issue end of last year. In recent times, the last time the data was accessible was in the beginning of this month; while the first time when the data wasn't accessible since the beginning of last week.

**Comment by jschaeff** [comment] 2020-10-26 15:40
Thank you. I think the problem is gone, but I'm not sure of what was the cause.
I still see some 401 HTTP responses, but can't tell if it is a real authentication problem or if the user entered a wrong credential.

I close this issue, please report back if the problem occurs again.

Kind regards

**Closed by jschaeff** 2020-10-26 15:40 UTC
Labels: Authentication/Authorization, node-RESIF

**Comment by okling** [comment] 2020-10-26 15:44
Okay. I will report back if the problem reappears.
Thanks again!
